name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build-dep
      run: |
        false || true
        pwd
        sudo apt -y update
        sudo apt -y install subversion g++ zlib1g-dev build-essential git python python3 python3-distutils libncurses5-dev gawk gettext unzip file libssl-dev wget libelf-dev ecj fastjar java-propose-classpath
        sudo apt clean

    - name: cleanup
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        docker rmi $(docker image ls -aq)
        df -h

    - name: fetch
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ./repo
        chmod +x ./repo
        mkdir build
        cd build
        ../repo init -u https://github.com/nswa-project/ranga.git -b master --depth 1
        ../repo sync

    - name: feeds
      run: |
        cd build/openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ../ranga/scripts/apply-feeds-patches.sh
 
    - name: compile
      run: |
        ./prebuild-dl.sh x86_64 build/openwrt
        #./buildbot.sh --configs x86_64 --openwrt-dir build/openwrt 2>&1
        ls -l build/openwrt || true
        echo ---
        ls -l build/openwrt/build_dir || true
        echo ---
        ls -l build/openwrt/staging_dir || true
        exit 1

    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./build/openwrt/bin
